/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ervalsa.kotlin.kotlin_fundamental

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

//fun main(args: Array<String>) {
//    println(App().greeting)
//}

// main function
fun main() {
    /* Hello kotlin print
       println("Hello Kotlin!")
    */

    val name = "Alfian"

    print("Hello my name is ")
    println(name)
    print(if (true) "Always true" else "Always false")
}